import {expect,test} from '@playwright/test';
import {mkdir,readFile,writeFile,rename,copyFile} from 'node:fs/promises';
import path from 'node:path';

const fixtureRoot = path.resolve('test-results/dashboard-browser-project');

test('narrative cross-scene backdrop reuse, crop, adaptation and independent subscene import',async({page})=>{
  test.setTimeout(90_000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  const story=await(await page.request.post('/api/narrative/stories',{data:{title:'Cross-scene references'}})).json();
  const sourceScene=await(await page.request.post(`/api/narrative/stories/${story.id}/scenes`,{data:{title:'Arrival',lighting:'Daylight'}})).json();
  const sourceSceneBase=`/api/narrative/stories/${story.id}/scenes/${sourceScene.id}`;
  const source=await(await page.request.post(sourceSceneBase+'/targets',{data:{title:'Arrival courtyard',kind:'backdrop',prompt:'Literal original courtyard prompt'}})).json();
  const sourceBase=sourceSceneBase+'/targets/'+source.id;
  await page.request.post(sourceBase+'/jobs',{data:{action:'render'}});
  await finish(page,sourceBase,'image');
  const completed=await(await page.request.get(sourceBase)).json();
  await page.request.post(sourceBase+`/candidates/${completed.slots[0]}`,{data:{action:'select'}});
  const traveler=await(await page.request.post(sourceSceneBase+'/elements',{data:{name:'Traveler',appearance:'Green cloak'}})).json();
  await page.request.post(sourceSceneBase+'/targets',{data:{title:'Arrival group',kind:'subscene',narrative:'A traveler arrives',element_ids:[traveler.id],prompt:'Historical subscene prompt'}});
  const destination=await(await page.request.post(`/api/narrative/stories/${story.id}/scenes`,{data:{title:'Second scene',lighting:'Moonlight'}})).json();
  const sceneBase=`/api/narrative/stories/${story.id}/scenes/${destination.id}`;
  await page.goto(`/narrative?story=${story.id}&scene=${destination.id}`);
  await page.getByRole('button',{name:'Reference backdrop from another scene',exact:true}).click();
  await expect(page.locator('#source-candidate')).toHaveValue(completed.slots[0]);
  await expect(page.locator('#source-preview')).toContainText('Literal original courtyard prompt');
  await page.getByRole('button',{name:'Create referenced backdrop',exact:true}).click();
  await expect(page.locator('#narrative-source-panel')).toContainText('Arrival courtyard');
  await expect(page.locator('#backdrop-source-image')).toBeVisible();
  await page.getByRole('button',{name:'Use unchanged image',exact:true}).click();
  await expect(page.locator('.narrative-slot.selected')).toHaveCount(1);
  const targetId=new URL(page.url()).searchParams.get('target');
  const base=sceneBase+'/targets/'+targetId;
  const reused=await(await page.request.get(base)).json();
  expect(Object.keys(reused.jobs)).toHaveLength(0);
  const originalBytes=await(await page.request.get(sourceBase+`/candidates/${completed.slots[0]}/image`)).body();
  expect(await(await page.request.get(base+`/candidates/${reused.selected_id}/image`)).body()).toEqual(originalBytes);
  await page.locator('#backdrop-operation').selectOption('crop');
  await page.locator('#narrative-width').fill('256');await page.locator('#narrative-height').fill('256');
  await page.locator('#backdrop-crop-zoom').evaluate(input=>{input.value='2';input.dispatchEvent(new Event('input',{bubbles:true}));});
  await page.getByRole('button',{name:'Create cropped image',exact:true}).click();
  await expect(page.locator('.narrative-slot img')).toHaveCount(2);
  await expect(page.getByRole('button',{name:'Generate 1 from inputs',exact:true})).toBeDisabled();
  await page.locator('#backdrop-operation').selectOption('viewpoint');
  await page.locator('#backdrop-direction').fill('Look back toward the entrance from the courtyard');
  await page.getByRole('button',{name:'Generate 1 from inputs',exact:true}).click();
  const adaptation=await finish(page,base,'generate',{scene:'Adapt the courtyard from the opposite viewpoint.',rendering:'Moonlight.'});
  expect(adaptation.references[0].role).toBe('backdrop source');
  expect(adaptation.detail.backdrop_adaptation.direction).toContain('Look back');
  await finish(page,base,'image');
  await expect(page.locator('.narrative-slot img')).toHaveCount(3);
  expect((await(await page.request.get(base)).json()).selected_id).toBe(reused.selected_id);
  await page.screenshot({path:'test-results/narrative-reference-backdrop.png',fullPage:true});
  await page.getByRole('link',{name:'Second scene',exact:true}).click();
  await page.getByRole('button',{name:'Import subscene from another scene',exact:true}).click();
  await expect(page.locator('#source-preview')).toContainText('Traveler');
  await page.getByRole('button',{name:'Import subscene',exact:true}).click();
  await expect(page.locator('#narrative-narrative')).toHaveValue('A traveler arrives');
  await expect(page.locator('#narrative-prompt')).toHaveValue('');
  const importedBase=sceneBase+'/targets/'+new URL(page.url()).searchParams.get('target');
  const imported=await(await page.request.get(importedBase)).json();
  expect(imported.elements[0].id).not.toBe(traveler.id);
  expect(imported.context.lighting).toBe('Moonlight');
  await page.locator('#narrative-direction').fill('Turn the traveler toward the gate');
  await page.getByRole('button',{name:'Continue interview',exact:true}).click();
  await finish(page,importedBase,'interview',{narrative:'The traveler turns toward the gate',staging:'Facing away',physical_context:'Stone floor',framing:'Full body',questions:[]});
  await expect(page.locator('#narrative-narrative')).toHaveValue('The traveler turns toward the gate');
  await page.getByRole('button',{name:'Generate 1 from inputs',exact:true}).click();
  const normal=await finish(page,importedBase,'generate',{scene:'Create a traveler turning toward the gate.',rendering:'Moonlight.'});
  expect(normal.references).toHaveLength(0);
  await finish(page,importedBase,'image');
  await expect(page.locator('.narrative-slot img')).toHaveCount(1);
  expect(errors).toEqual([]);
});

test('story cards show final assembly thumbnails and blanks for unfinished scenes',async({page})=>{
  const story = {id:'a'.repeat(32),title:'Story & <moon>',brief:'A journey',scenes:[
    {id:'b'.repeat(32),title:'Arrival',final_assembly:{target_id:'c'.repeat(32),candidate_id:'d'.repeat(32)}},
    {id:'e'.repeat(32),title:'No selected assembly',final_assembly:null},
    {id:'f'.repeat(32),title:'No assembly yet',final_assembly:null},
  ]};
  await page.route('**/api/narrative/stories',route=>route.fulfill({json:[story]}));
  await page.route('**/candidates/*/image?*',async route=>route.fulfill({contentType:'image/png',body:await readFile(path.join(fixtureRoot,'narrative-images/proposal.png'))}));
  await page.goto('/narrative');
  const card=page.locator('.narrative-card').filter({has:page.getByRole('link',{name:story.title,exact:true})});
  await expect(card.locator('.narrative-story-scene')).toHaveCount(3);
  await expect(card.locator('img')).toHaveCount(1);
  await expect.poll(()=>card.locator('img').evaluate(image=>image.naturalWidth)).toBeGreaterThan(0);
  await expect(card.locator('.narrative-story-placeholder')).toHaveCount(2);
  await expect(card.locator('.narrative-story-scene').nth(0)).toHaveAttribute('href',new RegExp(`story=${story.id}&scene=${story.scenes[0].id}&target=${story.scenes[0].final_assembly.target_id}`));
  await expect(card.locator('.narrative-story-scene').nth(1)).toHaveAttribute('href',new RegExp(`story=${story.id}&scene=${story.scenes[1].id}$`));
  await expect(page.locator('#new-story')).not.toBeVisible();
  await page.screenshot({path:'test-results/narrative-story-cards.png',fullPage:true});
});

async function finish(page,base,kind,payload) {
  await expect.poll(async()=>{
    const value=await(await page.request.get(base)).json();
    return Object.values(value.jobs).filter(item=>item.kind===kind).at(-1)?.status;
  }).toBe('QUEUED');
  const detail = await (await page.request.get(base)).json();
  const job = Object.values(detail.jobs).filter(item=>item.kind===kind).at(-1);
  const ask = path.join(fixtureRoot,'Queue/File_Proxy/Ask/zet',job.id);
  const answer = path.join(fixtureRoot,'Queue/File_Proxy/Answer/zet',job.id);
  const manifest = JSON.parse(await readFile(path.join(ask,'ask_manifest.json'),'utf8'));
  await rename(ask,answer);
  if (kind === 'image' && payload) await writeFile(path.join(answer,manifest.expected_output),payload);
  else if (kind === 'image') await copyFile(path.join(fixtureRoot,'Stories/Alpha-Story/Opening-Scene.png'),path.join(answer,manifest.expected_output));
  else await writeFile(path.join(answer,manifest.expected_output),JSON.stringify(payload));
  await writeFile(path.join(answer,'answer_manifest.json'),JSON.stringify({ask_id:job.id,status:'SUCCESS',expected_output:manifest.expected_output}));
  await writeFile(path.join(answer,'harvest_manifest.json'),'{}');
  return job;
}

test('empty assembly interview and prompt buttons publish Ollama jobs',async({page})=>{
  const story=await(await page.request.post('/api/narrative/stories',{data:{title:'Assembly planning'}})).json();
  const scene=await(await page.request.post(`/api/narrative/stories/${story.id}/scenes`,{data:{title:'Encounter'}})).json();
  const sceneBase=`/api/narrative/stories/${story.id}/scenes/${scene.id}`;
  const target=await(await page.request.post(sceneBase+'/targets',{data:{title:'Final assembly',kind:'assembly'}})).json();
  const base=sceneBase+'/targets/'+target.id;
  await page.goto(`/narrative?story=${story.id}&scene=${scene.id}&target=${target.id}`);
  await page.locator('#narrative-direction').fill('Plan a hopeful encounter.');
  await page.getByRole('button',{name:'Continue interview',exact:true}).click();
  await expect(page.locator('#narrative-job-status')).toContainText('interview: queued');
  await expect(page.locator('#narrative-job-status .narrative-pending')).toBeVisible();
  await expect(page.locator('#narrative-prompt')).toBeDisabled();
  await expect(page.getByRole('button',{name:'Write prompt',exact:true})).toBeDisabled();
  const interview=await finish(page,base,'interview',{narrative:'A hopeful encounter.',staging:'Facing inward',physical_context:'Paving',framing:'Wide',questions:[]});
  expect(interview.model).toBe('general:latest');
  await expect(page.locator('#narrative-narrative')).toHaveValue('A hopeful encounter.');
  await expect(page.locator('#narrative-prompt')).toBeEnabled();
  await expect(page.locator('#narrative-interview-status')).toContainText('New interview answer received');
  await page.getByRole('button',{name:'Write prompt',exact:true}).click();
  await expect(page.locator('#narrative-job-status')).toContainText('synthesize: queued');
  await expect(page.locator('#narrative-prompt')).toBeDisabled();
  const prompt=await finish(page,base,'synthesize',{scene:'Create a hopeful encounter.',rendering:'Soft daylight.'});
  expect(prompt.model).toBe('general:latest');
  await expect(page.locator('#narrative-prompt')).toHaveValue(/Soft daylight/);
  await expect(page.locator('#narrative-prompt')).toBeEnabled();
  await page.getByRole('button',{name:'Write prompt',exact:true}).click();
  await finish(page,base,'synthesize',{});
  await expect(page.locator('#narrative-job-status .narrative-failure')).toContainText('no usable scene or rendering prose');
  await expect(page.locator('#narrative-prompt')).toBeEnabled();
  await expect(page.locator('#narrative-prompt')).toHaveValue(/Soft daylight/);
});

test('model selectors, exact reruns, output history and manual provenance',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  let discoveryFails=false;
  await page.route('**/api/ai-controls/ollama-models**',route=>route.fulfill({status:discoveryFails?503:200,contentType:'application/json',body:JSON.stringify(discoveryFails?{detail:'Discovery unavailable'}:{models:['general:latest','other:latest']})}));
  const story=await(await page.request.post('/api/narrative/stories',{data:{title:'Model switching'}})).json();
  const scene=await(await page.request.post(`/api/narrative/stories/${story.id}/scenes`,{data:{title:'Encounter'}})).json();
  const sceneBase=`/api/narrative/stories/${story.id}/scenes/${scene.id}`;
  const target=await(await page.request.post(sceneBase+'/targets',{data:{title:'Traveler',narrative:'Original moment'}})).json();
  const base=sceneBase+'/targets/'+target.id;
  await page.goto(`/narrative?story=${story.id}&scene=${scene.id}&target=${target.id}`);
  await expect(page.locator('#narrative-prompt_model')).toBeVisible();
  await expect(page.getByRole('button',{name:'Refresh models',exact:true})).toHaveCount(0);
  await expect(page.locator('#narrative-model-options option[value="other:latest"]')).toHaveCount(1);
  await expect(page.locator('#narrative-model-options option[value="codex:gpt-6-sol"]')).toHaveCount(1);
  await page.locator('#narrative-interview_model').fill('other:latest');
  await page.locator('#narrative-direction').fill('Make the traveler hopeful.');
  await page.getByRole('button',{name:'Continue interview',exact:true}).click();
  await expect(page.locator('#narrative-job-status')).toContainText('interview: queued');
  const firstInterview=Object.values((await(await page.request.get(base)).json()).jobs).filter(job=>job.kind==='interview').at(-1);
  await finish(page,base,'interview',{narrative:'A hopeful traveler arrives.',staging:'Facing inward',physical_context:'Paving',framing:'Full body',questions:[]});
  await expect(page.locator('#narrative-interview')).toContainText('other:latest');
  await page.locator('#narrative-interview_model').fill('general:latest');
  await page.locator('#narrative-narrative').fill('A changed current moment');
  await page.getByRole('button',{name:'Re-run last interview',exact:true}).click();
  await expect(page.locator('#narrative-job-status')).toContainText('interview: queued');
  const secondInterview=Object.values((await(await page.request.get(base)).json()).jobs).filter(job=>job.kind==='interview').at(-1);
  expect(secondInterview.request).toBe(firstInterview.request);
  expect(secondInterview.model).toBe('general:latest');
  await finish(page,base,'interview',{narrative:'Another hopeful output.',staging:'Three quarter view',physical_context:'Paving',framing:'Full body',questions:['A long answer. '.repeat(200)]});
  await expect(page.locator('#narrative-interview .narrative-history-entry')).toHaveCount(4);
  await expect(page.locator('#narrative-interview .narrative-new-reply')).toHaveCount(1);
  expect(await page.locator('#narrative-interview').evaluate(history=>{
    const reply=history.lastElementChild;
    return Math.abs(reply.getBoundingClientRect().top-history.getBoundingClientRect().top)<5;
  })).toBe(true);
  await page.getByRole('button',{name:'Write prompt',exact:true}).click();
  await finish(page,base,'synthesize',{scene:'First generated prompt.',rendering:'Soft light.'});
  await expect(page.locator('#narrative-prompt')).toHaveValue(/First generated prompt/);
  const firstPrompt=Object.values((await(await page.request.get(base)).json()).jobs).filter(job=>job.kind==='synthesize').at(-1);
  await page.locator('#narrative-prompt_model').fill('other:latest');
  await page.getByRole('button',{name:'Re-run last prompt',exact:true}).click();
  await expect(page.locator('#narrative-job-status')).toContainText('synthesize: queued');
  const secondPrompt=Object.values((await(await page.request.get(base)).json()).jobs).filter(job=>job.kind==='synthesize').at(-1);
  expect(secondPrompt.request).toBe(firstPrompt.request);
  await finish(page,base,'synthesize',{scene:'Second generated prompt.',rendering:'Warmer light.'});
  await expect(page.locator('#narrative-prompt-origin')).toHaveText('other:latest');
  await page.getByText('Previous prompt outputs',{exact:true}).click();
  await page.locator('#narrative-prompt-history').selectOption(firstPrompt.id);
  await expect(page.locator('#narrative-prompt-preview')).toContainText('First generated prompt');
  await page.getByRole('button',{name:'Use this prompt',exact:true}).click();
  await expect(page.locator('#narrative-prompt-origin')).toHaveText('general:latest');
  await page.locator('#narrative-prompt').fill('My literal revision');
  await page.getByRole('button',{name:'Save inputs',exact:true}).click();
  await expect(page.locator('#narrative-prompt-origin')).toContainText('Manually edited');
  await page.locator('#narrative-prompt_model').fill('codex:gpt-6-sol');
  await page.getByRole('button',{name:'Save inputs',exact:true}).click();
  discoveryFails=true;
  await page.reload();
  await expect(page.locator('#narrative-model-error')).toHaveText('Discovery unavailable');
  await expect(page.locator('#narrative-prompt_model')).toHaveValue('codex:gpt-6-sol');
  await page.reload();
  await expect(page.locator('#narrative-prompt_model')).toHaveValue('codex:gpt-6-sol');
  await expect(page.locator('#narrative-interview_model')).toHaveValue('general:latest');
  await expect(page.locator('#narrative-prompt-origin')).toContainText('general:latest · Manually edited');
  expect(errors).toEqual([]);
});

test('final assembly source placement, cutout corrections, finishing and selected download',async({page})=>{
  test.setTimeout(90_000);
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/api/ai-controls/ollama-models**',route=>route.fulfill({json:{models:['general:latest']}}));
  const story=await(await page.request.post('/api/narrative/stories',{data:{title:'Assembly browser'}})).json();
  const scene=await(await page.request.post(`/api/narrative/stories/${story.id}/scenes`,{data:{title:'Courtyard'}})).json();
  const sceneBase=`/api/narrative/stories/${story.id}/scenes/${scene.id}`;
  const sources=[];
  for(const [kind,title] of [['backdrop','Blue backdrop'],['subscene','Traveler group']]) {
    const target=await(await page.request.post(sceneBase+'/targets',{data:{title,kind,prompt:'Source prompt'}})).json();
    const base=sceneBase+'/targets/'+target.id;
    await page.request.post(base+'/jobs',{data:{action:'render'}});
    await finish(page,base,'image',await readFile(path.join(fixtureRoot,'narrative-images',kind==='backdrop'?'backdrop.png':'group.png')));
    const completed=await(await page.request.get(base)).json();
    await page.request.post(base+`/candidates/${completed.slots[0]}`,{data:{action:'select'}});
    sources.push(target);
  }
  await page.goto(`/narrative?story=${story.id}&scene=${scene.id}`);
  await page.getByRole('button',{name:'Create final assembly',exact:true}).click();
  await expect(page.locator('#assembly-source')).toBeVisible();
  const url=new URL(page.url()),base=sceneBase+'/targets/'+url.searchParams.get('target');
  await page.locator('#narrative-width').fill('256');await page.locator('#narrative-height').fill('256');
  await page.locator('#assembly-source').selectOption(sources[0].id);
  await page.getByRole('button',{name:'Add selected image',exact:true}).click();
  await expect(page.locator('.narrative-layer')).toHaveCount(1);
  await page.locator('#assembly-source').selectOption(sources[1].id);
  await page.getByRole('button',{name:'Add selected image',exact:true}).click();
  await expect(page.locator('.narrative-layer')).toHaveCount(2);
  const record=await(await page.request.get(base)).json(),groupId=record.layers[1].id;
  const scale=page.locator(`[data-layer="${groupId}"][data-layer-field="scale"]`);
  await scale.fill('.5');await scale.press('Tab');
  await expect(page.locator('#narrative-message')).toHaveText('Saved');
  const placement=page.locator(`[data-drag-layer="${groupId}"]`);
  await placement.scrollIntoViewIfNeeded();
  await expect.poll(()=>placement.locator('img').evaluate(image=>image.complete&&image.naturalHeight>0)).toBe(true);
  const box=await placement.boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+20,box.y+box.height/2+10);await page.mouse.up();
  await page.getByRole('button',{name:'Save inputs',exact:true}).click();
  const placed=await(await page.request.get(base)).json();
  expect(placed.layers[1].x).toBeGreaterThan(.1);
  await page.locator(`[data-mask-layer="${groupId}"]`).click();
  await expect(page.locator('#mask-canvas')).toBeVisible();
  await page.locator('#mask-mode').selectOption('remove');
  await page.locator('#mask-canvas').click({position:{x:5,y:5}});
  await page.getByRole('button',{name:'Save corrections',exact:true}).click();
  await page.getByRole('button',{name:'Close',exact:true}).click();
  expect((await(await page.request.get(base)).json()).layers[1].strokes).toHaveLength(1);
  await page.getByRole('button',{name:'Refresh raw composite',exact:true}).click();
  await expect(page.locator('#assembly-raw')).toBeVisible();
  const rawDownload=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download raw composite',exact:true}).click();
  expect((await rawDownload).suggestedFilename()).toBe('composite.png');
  await page.locator('#narrative-narrative').fill('A traveler arrives in the courtyard.');
  await page.getByRole('button',{name:'Generate 1 from inputs',exact:true}).click();
  await finish(page,base,'generate',{scene:'Finish the assembled traveler scene.',rendering:'Blend joins and contact shadows.'});
  await expect(page.locator('#narrative-prompt')).toHaveValue(/assembled final scene/);
  await finish(page,base,'image',await readFile(path.join(fixtureRoot,'narrative-images','proposal.png')));
  await expect(page.locator('.narrative-slot').first().locator('img')).toBeVisible();
  await page.locator('.narrative-slot').first().getByRole('button',{name:'Select',exact:true}).click();
  await page.locator('.narrative-slot').first().getByRole('button',{name:'Lock',exact:true}).click();
  await page.reload();
  await expect(page.locator('.narrative-slot').first()).toContainText('Selected · Locked');
  await expect(page.locator(`[data-layer="${groupId}"][data-layer-field="scale"]`)).toHaveValue('0.5');
  await expect(page.locator('.narrative-slot')).toHaveCount(8);
  await page.locator('.narrative-slot').first().getByText('Prompt and source',{exact:true}).click();
  await expect(page.locator('.narrative-slot').first()).toContainText('general:latest');
  await expect(page.locator('.narrative-slot').first().getByRole('link',{name:'Compare raw composite'})).toBeVisible();
  await expect(page.locator('.narrative-slot').getByRole('link',{name:'Download',exact:true})).toHaveCount(0);
  await expect(page.locator('#narrative-assembly_mode')).toHaveValue('finish_composite');
  const oldPrompt=await page.locator('#narrative-prompt').inputValue();
  await page.locator('#narrative-assembly_mode').selectOption('assemble_references');
  await expect(page.locator('#narrative-assembly-prompt-warning')).toContainText('another assembly mode');
  await expect(page.getByRole('button',{name:'Render edited prompt · 1',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Save inputs',exact:true}).click();
  await page.reload();
  await expect(page.locator('#narrative-assembly_mode')).toHaveValue('assemble_references');
  await expect(page.locator('#narrative-prompt')).toHaveValue(oldPrompt);
  await expect(page.locator('#narrative-assembly-help')).toContainText('original sources');
  await page.getByRole('button',{name:'Write prompt',exact:true}).click();
  const referencePrompt=await finish(page,base,'synthesize',{scene:'Assemble the traveler in the courtyard.',rendering:'Natural contact shadows.'});
  await expect(page.locator('#narrative-prompt')).toHaveValue(/full source-image rectangle/);
  await expect(page.getByRole('button',{name:'Render edited prompt · 1',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Render edited prompt · 1',exact:true}).click();
  const referenceJob=await finish(page,base,'image',await readFile(path.join(fixtureRoot,'narrative-images','proposal.png')));
  const referenceDetail=await(await page.request.get(base)).json();
  const referenceCandidate=referenceDetail.candidates[referenceJob.candidate_id];
  expect(referenceCandidate.assembly_mode).toBe('assemble_references');
  expect(referenceCandidate.assembly_snapshot.references).toHaveLength(2);
  const referenceSlot=page.locator('.narrative-slot').nth(referenceCandidate.slot-1);
  await expect(referenceSlot.locator('img')).toBeVisible();
  await referenceSlot.getByText('Prompt and source',{exact:true}).click();
  await expect(referenceSlot).toContainText('Assemble from references');
  await expect(referenceSlot.getByRole('link',{name:'Compare raw composite'})).toHaveCount(0);
  await page.locator('#narrative-assembly_mode').selectOption('finish_composite');
  await page.getByRole('button',{name:'Save inputs',exact:true}).click();
  await page.getByText('Previous prompt outputs',{exact:true}).click();
  await page.locator('#narrative-prompt-history').selectOption(referencePrompt.id);
  await page.getByRole('button',{name:'Use this prompt',exact:true}).click();
  await expect(page.locator('#narrative-assembly_mode')).toHaveValue('assemble_references');
  await page.screenshot({path:'test-results/narrative-phase2-assembly.png',fullPage:true});
  expect(errors).toEqual([]);
});

test('narrative setup, own subscene page, interview, rendering and protected selection',async({page})=>{
  test.setTimeout(90_000);
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/narrative');
  await expect(page.locator('#new-story')).not.toBeVisible();
  await page.getByRole('button',{name:'New Story',exact:true}).click();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(page.locator('#story-dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'New Story',exact:true}).click();
  await expect(page.locator('#new-story')).toBeVisible();
  await page.locator('#new-story input[name=title]').fill('Browser narrative story');
  await page.getByRole('button',{name:'Create story',exact:true}).click();
  await expect(page.locator('#new-scene')).toBeVisible();
  await page.getByRole('textbox',{name:'Scene title',exact:true}).fill('New encounter');
  await page.getByRole('button',{name:'Create scene',exact:true}).click();
  await expect(page.locator('#new-target')).toBeVisible();
  await page.locator('#narrative-camera').fill('Camera at chest height');
  await page.getByRole('button',{name:'Save scene',exact:true}).click();
  await expect(page.locator('#narrative-message')).toHaveText('Saved');
  await page.getByRole('button',{name:'Add element',exact:true}).click();
  await page.locator('#element-form input[name=name]').fill('Traveler');
  await page.locator('#element-form textarea[name=appearance]').fill('A cloaked traveler carrying a staff');
  await page.getByRole('button',{name:'Save element',exact:true}).click();
  await expect(page.locator('#element-dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'Add element',exact:true}).click();
  await page.locator('#element-form input[name=name]').fill('Unrelated spectator');
  await page.getByRole('button',{name:'Save element',exact:true}).click();
  await expect(page.locator('#element-dialog')).not.toBeVisible();
  await page.getByRole('textbox',{name:'Target title',exact:true}).fill('Traveler arriving');
  await page.getByRole('button',{name:'Create and edit',exact:true}).click();
  await expect(page.locator('#narrative-prompt')).toBeVisible();
  await expect(page.locator('.narrative-slot')).toHaveCount(8);
  await page.getByRole('button',{name:'Assign scene elements',exact:true}).click();
  await page.getByRole('checkbox',{name:'Traveler · subject',exact:true}).check();
  await page.getByRole('button',{name:'Save assignments',exact:true}).click();
  await expect(page.locator('#membership-dialog')).not.toBeVisible();
  await expect(page.locator('#narrative-elements')).toContainText('Traveler');
  await expect(page.locator('#narrative-elements')).not.toContainText('Unrelated spectator');
  await expect(page.locator('.narrative-context')).toContainText('Camera at chest height');
  await page.locator('#narrative-narrative').fill('A traveler pauses uncertainly at an academy gate.');
  await page.locator('#narrative-direction').fill('Make the reaction quietly hopeful.');
  await page.getByRole('button',{name:'Continue interview',exact:true}).click();
  await expect(page.locator('#narrative-job-status')).toContainText('interview: queued');
  const url = new URL(page.url());
  const base = `/api/narrative/stories/${url.searchParams.get('story')}/scenes/${url.searchParams.get('scene')}/targets/${url.searchParams.get('target')}`;
  await finish(page,base,'interview',{narrative:'A traveler pauses at the gate with quiet hope.',staging:'Facing inward in three-quarter view.',physical_context:'Stone paving.',framing:'Full body',questions:['Should the staff be raised?']});
  await expect(page.locator('#narrative-narrative')).toHaveValue('A traveler pauses at the gate with quiet hope.');
  await expect(page.locator('#narrative-interview')).toContainText('Should the staff be raised?');
  await page.getByRole('button',{name:'Generate 1 from inputs',exact:true}).click();
  await expect(page.locator('#narrative-job-status')).toContainText('generate: queued');
  await finish(page,base,'generate',{scene:'Create an illustration of a hopeful traveler pausing at the gate.',rendering:'Chest-height camera, soft daylight.'});
  await expect(page.locator('#narrative-prompt')).toHaveValue(/Chest-height camera/);
  await expect(page.locator('.narrative-slot').first()).toContainText('queued');
  await finish(page,base,'image');
  await expect(page.locator('.narrative-slot').first().locator('img')).toBeVisible();
  await page.locator('.narrative-slot').first().getByRole('button',{name:'Select',exact:true}).click();
  await expect(page.locator('.narrative-slot').first()).toContainText('Selected');
  await page.locator('#narrative-narrative').fill('New direction after image selection.');
  await page.getByRole('button',{name:'Save inputs',exact:true}).click();
  await expect(page.locator('#narrative-message')).toHaveText('Saved');
  await page.reload();
  await expect(page.locator('.narrative-slot').first()).toContainText('Selected');
  await expect(page.locator('#narrative-narrative')).toHaveValue('New direction after image selection.');
  let dialogHandled = new Promise(resolve=>page.once('dialog',async dialog=>{await dialog.dismiss();resolve();}));
  await page.locator('.narrative-slot').first().getByRole('button',{name:'Clear',exact:true}).click();
  await dialogHandled;
  await expect(page.locator('.narrative-slot').first().getByRole('button',{name:'Clear',exact:true})).toBeEnabled();
  await expect(page.locator('.narrative-slot').first()).toContainText('Selected');
  await page.screenshot({path:'test-results/narrative-editor.png',fullPage:true});
  dialogHandled = new Promise(resolve=>page.once('dialog',async dialog=>{await dialog.accept();resolve();}));
  await page.locator('.narrative-slot').first().getByRole('button',{name:'Clear',exact:true}).click();
  await dialogHandled;
  await expect(page.locator('.narrative-slot').first()).toContainText('Empty');
  expect(errors).toEqual([]);
});

test('narrative image review navigates, selects, regenerates and clears',async({page})=>{
  await page.addInitScript(()=>{
    Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedPrompt=text;}}});
  });
  const story=await(await page.request.post('/api/narrative/stories',{data:{title:'Image review controls'}})).json();
  const sceneBase=`/api/narrative/stories/${story.id}/scenes`;
  const scene=await(await page.request.post(sceneBase,{data:{title:'Review scene'}})).json();
  const target=await(await page.request.post(`${sceneBase}/${scene.id}/targets`,{data:{title:'Traveler',prompt:'Render a traveler.'}})).json();
  const base=`${sceneBase}/${scene.id}/targets/${target.id}`;
  await page.goto(`/narrative?story=${story.id}&scene=${scene.id}&target=${target.id}`);
  for (const slot of [1,2]) {
    await page.locator(`[data-render-slot="${slot}"]`).click();
    await finish(page,base,'image');
    await expect(page.locator('.narrative-slot').nth(slot-1).locator('img')).toBeVisible();
  }
  await expect(page.locator('.narrative-slot').getByRole('link',{name:'Download',exact:true})).toHaveCount(0);
  await page.locator('.narrative-slot').first().locator('img').click();
  const review=page.getByRole('dialog',{name:'Image review',exact:true});
  await expect(review).toBeVisible();
  await expect(review.getByRole('button',{name:'Previous candidate'})).toBeDisabled();
  await expect(review.locator('#narrative-review-panel')).toContainText('1 of 2');
  await review.getByRole('button',{name:'Copy prompt to clipboard'}).click();
  await expect.poll(()=>page.evaluate(()=>window.copiedPrompt)).toBe('Render a traveler.');
  const actionRows=await review.locator('.local-pipeline-review-actions button').evaluateAll(buttons=>buttons.map(button=>button.getBoundingClientRect().top));
  expect(new Set(actionRows).size).toBe(1);
  await review.getByRole('button',{name:'Select',exact:true}).click();
  await expect(review.locator('#narrative-review-panel')).toContainText('Selected');
  await expect(review.getByRole('button',{name:'Regen',exact:true})).toBeDisabled();
  await review.getByRole('button',{name:'Next candidate'}).click();
  await expect(review.locator('#review-image')).toHaveAttribute('alt','Slot 2 candidate');
  await expect(review.getByRole('button',{name:'Next candidate'})).toBeDisabled();
  await review.getByRole('button',{name:'Previous candidate'}).click();
  await expect(review.locator('#review-image')).toHaveAttribute('alt','Slot 1 candidate');
  await review.getByRole('button',{name:'Next candidate'}).click();
  await review.getByRole('button',{name:'Regen',exact:true}).click();
  await expect(page.locator('.narrative-slot').nth(1)).toContainText('queued');
  await expect(review.locator('#review-image')).toHaveAttribute('alt','Slot 1 candidate');
  await finish(page,base,'image');
  await expect(review.getByRole('button',{name:'Next candidate'})).toBeEnabled();
  await review.getByRole('button',{name:'Next candidate'}).click();
  await review.getByRole('button',{name:'Clear',exact:true}).click();
  await expect(page.locator('.narrative-slot').nth(1)).toContainText('Empty');
  await expect(review.locator('#narrative-review-panel')).toContainText('1 of 1');
  await page.screenshot({path:'test-results/narrative-image-review.png'});
  await review.getByRole('button',{name:'Close',exact:true}).click();
  await expect(review).not.toBeVisible();
});

test('backdrop has own inputs, no automatic cast and verbatim prompt rendering',async({page})=>{
  const story = await (await page.request.post('/api/narrative/stories',{data:{title:'Backdrop test'}})).json();
  const scene = await (await page.request.post(`/api/narrative/stories/${story.id}/scenes`,{data:{title:'Courtyard'}})).json();
  await page.request.post(`/api/narrative/stories/${story.id}/scenes/${scene.id}/elements`,{data:{name:'Unrelated character'}});
  const target = await (await page.request.post(`/api/narrative/stories/${story.id}/scenes/${scene.id}/targets`,{data:{title:'Academy backdrop',kind:'backdrop'}})).json();
  const base = `/api/narrative/stories/${story.id}/scenes/${scene.id}/targets/${target.id}`;
  await page.goto(`/narrative?story=${story.id}&scene=${scene.id}&target=${target.id}`);
  await expect(page.locator('#narrative-elements')).not.toContainText('Unrelated character');
  await expect(page.locator('#narrative-width')).toHaveValue('1344');
  await page.locator('#narrative-prompt').fill('My exact environment prompt.\nNegative constraints: literal prose.');
  await page.getByRole('button',{name:'Render edited prompt · 1',exact:true}).click();
  await expect(page.locator('.narrative-slot').first()).toContainText('queued');
  const detail = await (await page.request.get(base)).json();
  const job = Object.values(detail.jobs).find(item=>item.kind==='image');
  const prompt = await readFile(path.join(fixtureRoot,'Queue/File_Proxy/Ask/zet',job.id,'prompt.md'),'utf8');
  expect(prompt).toBe('My exact environment prompt.\nNegative constraints: literal prose.');
  await finish(page,base,'image');
  await expect(page.locator('.narrative-slot').first().locator('img')).toBeVisible();
});

test('scene cards show selected images, put backdrops first and switch detail pages while saving edits',async({page})=>{
  const story = await (await page.request.post('/api/narrative/stories',{data:{title:'Navigation test'}})).json();
  const sceneBase = `/api/narrative/stories/${story.id}/scenes`;
  const scene = await (await page.request.post(sceneBase,{data:{title:'Scene navigation'}})).json();
  const targetBase = `${sceneBase}/${scene.id}/targets`;
  const create = async(title,kind)=> (await page.request.post(targetBase,{data:{title,kind}})).json();
  const first = await create('Arrival','subscene');
  const backdrop = await create('Courtyard','backdrop');
  const second = await create('Exchange','subscene');
  for (const target of [first,backdrop]) {
    const base = `${targetBase}/${target.id}`;
    await page.request.patch(base,{data:{prompt:'Test image'}});
    await page.request.post(base+'/jobs',{data:{action:'render'}});
    await finish(page,base,'image');
    const detail = await (await page.request.get(base)).json();
    await page.request.post(base+`/candidates/${detail.slots[0]}`,{data:{action:'select'}});
  }
  await page.goto(`/narrative?story=${story.id}&scene=${scene.id}`);
  const cards = page.locator('.narrative-target-card');
  await expect(cards).toHaveCount(3);
  await expect(cards.nth(0)).toHaveAttribute('data-target-id',backdrop.id);
  await expect(cards.nth(1)).toHaveAttribute('data-target-id',first.id);
  await expect(cards.nth(2)).toHaveAttribute('data-target-id',second.id);
  await expect(cards.nth(2).locator('img')).toHaveCount(0);
  for (const card of [cards.nth(0),cards.nth(1)]) {
    const image = card.locator('img');
    await expect(image).toBeVisible();
    await expect.poll(()=>image.evaluate(img=>img.complete && img.naturalWidth > 0)).toBe(true);
  }
  await cards.nth(1).locator('img').click();
  const picker = page.getByRole('combobox',{name:'Scene page',exact:true});
  await expect(picker).toHaveValue(first.id);
  await expect(picker.locator('option')).toHaveText(['Courtyard · Backdrop','Arrival · Subscene','Exchange · Subscene']);
  await page.locator('#narrative-narrative').fill('A revised arrival before switching pages.');
  await picker.selectOption(backdrop.id);
  await expect(picker).toHaveValue(backdrop.id);
  await expect(page.locator('#narrative-width')).toHaveValue('1344');
  const saved = await (await page.request.get(`${targetBase}/${first.id}`)).json();
  expect(saved.narrative).toBe('A revised arrival before switching pages.');
  await picker.selectOption(second.id);
  await expect(picker).toHaveValue(second.id);
  await expect(page.locator('#narrative-title')).toHaveValue('Exchange');
  await page.locator('#narrative-title').fill('New exchange');
  await page.getByRole('button',{name:'Save inputs',exact:true}).click();
  await expect(picker.locator('option:checked')).toHaveText('New exchange · Subscene');
  await page.goBack();
  await expect(picker).toHaveValue(backdrop.id);
  await picker.selectOption(first.id);
  await expect(picker).toHaveValue(first.id);
  await expect(page.locator('#narrative-narrative')).toHaveValue('A revised arrival before switching pages.');
});
