import {expect,test} from '@playwright/test';
import {mkdir,readFile,writeFile,rename,copyFile} from 'node:fs/promises';
import path from 'node:path';

const fixtureRoot = path.resolve('test-results/dashboard-browser-project');

async function finish(page,base,kind,payload) {
  const detail = await (await page.request.get(base)).json();
  const job = Object.values(detail.jobs).filter(item=>item.kind===kind).at(-1);
  const ask = path.join(fixtureRoot,'Queue/File_Proxy/Ask/zet',job.id);
  const answer = path.join(fixtureRoot,'Queue/File_Proxy/Answer/zet',job.id);
  const manifest = JSON.parse(await readFile(path.join(ask,'ask_manifest.json'),'utf8'));
  await rename(ask,answer);
  if (kind === 'image') await copyFile(path.join(fixtureRoot,'Stories/Alpha-Story/Opening-Scene.png'),path.join(answer,manifest.expected_output));
  else await writeFile(path.join(answer,manifest.expected_output),JSON.stringify(payload));
  await writeFile(path.join(answer,'answer_manifest.json'),JSON.stringify({ask_id:job.id,status:'SUCCESS',expected_output:manifest.expected_output}));
  await writeFile(path.join(answer,'harvest_manifest.json'),'{}');
  return job;
}

test('narrative setup, own subscene page, interview, rendering and protected selection',async({page})=>{
  test.setTimeout(90_000);
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('/narrative');
  await expect(page.locator('#new-story')).toBeVisible();
  await page.locator('#new-story input[name=title]').fill('Browser narrative story');
  await page.getByRole('button',{name:'Create story',exact:true}).click();
  await expect(page.locator('#new-scene')).toBeVisible();
  await page.getByRole('textbox',{name:'Scene title',exact:true}).fill('New encounter');
  await page.getByRole('button',{name:'Create scene',exact:true}).click();
  await expect(page.locator('#new-target')).toBeVisible();
  await page.locator('#narrative-camera').fill('Camera at chest height');
  await page.getByRole('button',{name:'Save scene',exact:true}).click();
  await expect(page.locator('#narrative-message')).toHaveText('Saved');
  await page.getByRole('button',{name:'Add element',exact:true}).click();
  await page.locator('#element-form input[name=name]').fill('Traveler');
  await page.locator('#element-form textarea[name=appearance]').fill('A cloaked traveler carrying a staff');
  await page.getByRole('button',{name:'Save element',exact:true}).click();
  await expect(page.locator('#element-dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'Add element',exact:true}).click();
  await page.locator('#element-form input[name=name]').fill('Unrelated spectator');
  await page.getByRole('button',{name:'Save element',exact:true}).click();
  await expect(page.locator('#element-dialog')).not.toBeVisible();
  await page.getByRole('textbox',{name:'Target title',exact:true}).fill('Traveler arriving');
  await page.getByRole('button',{name:'Create and edit',exact:true}).click();
  await expect(page.locator('#narrative-prompt')).toBeVisible();
  await expect(page.locator('.narrative-slot')).toHaveCount(8);
  await page.getByRole('button',{name:'Assign scene elements',exact:true}).click();
  await page.getByRole('checkbox',{name:'Traveler · subject',exact:true}).check();
  await page.getByRole('button',{name:'Save assignments',exact:true}).click();
  await expect(page.locator('#membership-dialog')).not.toBeVisible();
  await expect(page.locator('#narrative-elements')).toContainText('Traveler');
  await expect(page.locator('#narrative-elements')).not.toContainText('Unrelated spectator');
  await expect(page.locator('.narrative-context')).toContainText('Camera at chest height');
  await page.locator('#narrative-narrative').fill('A traveler pauses uncertainly at an academy gate.');
  await page.locator('#narrative-direction').fill('Make the reaction quietly hopeful.');
  await page.getByRole('button',{name:'Continue interview',exact:true}).click();
  await expect(page.locator('#narrative-job-status')).toContainText('interview: queued');
  const url = new URL(page.url());
  const base = `/api/narrative/stories/${url.searchParams.get('story')}/scenes/${url.searchParams.get('scene')}/targets/${url.searchParams.get('target')}`;
  await finish(page,base,'interview',{narrative:'A traveler pauses at the gate with quiet hope.',staging:'Facing inward in three-quarter view.',physical_context:'Stone paving.',framing:'Full body',questions:['Should the staff be raised?']});
  await expect(page.locator('#narrative-narrative')).toHaveValue('A traveler pauses at the gate with quiet hope.');
  await expect(page.locator('#narrative-interview')).toContainText('Should the staff be raised?');
  await page.getByRole('button',{name:'Generate 1 from inputs',exact:true}).click();
  await expect(page.locator('#narrative-job-status')).toContainText('generate: queued');
  await finish(page,base,'generate',{scene:'Create an illustration of a hopeful traveler pausing at the gate.',rendering:'Chest-height camera, soft daylight.'});
  await expect(page.locator('#narrative-prompt')).toHaveValue(/Chest-height camera/);
  await expect(page.locator('.narrative-slot').first()).toContainText('queued');
  await finish(page,base,'image');
  await expect(page.locator('.narrative-slot').first().locator('img')).toBeVisible();
  await page.locator('.narrative-slot').first().getByRole('button',{name:'Select',exact:true}).click();
  await expect(page.locator('.narrative-slot').first()).toContainText('Selected');
  await page.locator('#narrative-narrative').fill('New direction after image selection.');
  await page.getByRole('button',{name:'Save inputs',exact:true}).click();
  await expect(page.locator('#narrative-message')).toHaveText('Saved');
  await page.reload();
  await expect(page.locator('.narrative-slot').first()).toContainText('Selected');
  await expect(page.locator('#narrative-narrative')).toHaveValue('New direction after image selection.');
  let dialogHandled = new Promise(resolve=>page.once('dialog',async dialog=>{await dialog.dismiss();resolve();}));
  await page.locator('.narrative-slot').first().getByRole('button',{name:'Clear',exact:true}).click();
  await dialogHandled;
  await expect(page.locator('.narrative-slot').first().getByRole('button',{name:'Clear',exact:true})).toBeEnabled();
  await expect(page.locator('.narrative-slot').first()).toContainText('Selected');
  await page.screenshot({path:'test-results/narrative-editor.png',fullPage:true});
  dialogHandled = new Promise(resolve=>page.once('dialog',async dialog=>{await dialog.accept();resolve();}));
  await page.locator('.narrative-slot').first().getByRole('button',{name:'Clear',exact:true}).click();
  await dialogHandled;
  await expect(page.locator('.narrative-slot').first()).toContainText('Empty');
  expect(errors).toEqual([]);
});

test('backdrop has own inputs, no automatic cast and verbatim prompt rendering',async({page})=>{
  const story = await (await page.request.post('/api/narrative/stories',{data:{title:'Backdrop test'}})).json();
  const scene = await (await page.request.post(`/api/narrative/stories/${story.id}/scenes`,{data:{title:'Courtyard'}})).json();
  await page.request.post(`/api/narrative/stories/${story.id}/scenes/${scene.id}/elements`,{data:{name:'Unrelated character'}});
  const target = await (await page.request.post(`/api/narrative/stories/${story.id}/scenes/${scene.id}/targets`,{data:{title:'Academy backdrop',kind:'backdrop'}})).json();
  const base = `/api/narrative/stories/${story.id}/scenes/${scene.id}/targets/${target.id}`;
  await page.goto(`/narrative?story=${story.id}&scene=${scene.id}&target=${target.id}`);
  await expect(page.locator('#narrative-elements')).not.toContainText('Unrelated character');
  await expect(page.locator('#narrative-width')).toHaveValue('1344');
  await page.locator('#narrative-prompt').fill('My exact environment prompt.\nNegative constraints: literal prose.');
  await page.getByRole('button',{name:'Render edited prompt · 1',exact:true}).click();
  await expect(page.locator('.narrative-slot').first()).toContainText('queued');
  const detail = await (await page.request.get(base)).json();
  const job = Object.values(detail.jobs).find(item=>item.kind==='image');
  const prompt = await readFile(path.join(fixtureRoot,'Queue/File_Proxy/Ask/zet',job.id,'prompt.md'),'utf8');
  expect(prompt).toBe('My exact environment prompt.\nNegative constraints: literal prose.');
  await finish(page,base,'image');
  await expect(page.locator('.narrative-slot').first().locator('img')).toBeVisible();
});

test('scene cards show selected images, put backdrops first and switch detail pages while saving edits',async({page})=>{
  const story = await (await page.request.post('/api/narrative/stories',{data:{title:'Navigation test'}})).json();
  const sceneBase = `/api/narrative/stories/${story.id}/scenes`;
  const scene = await (await page.request.post(sceneBase,{data:{title:'Scene navigation'}})).json();
  const targetBase = `${sceneBase}/${scene.id}/targets`;
  const create = async(title,kind)=> (await page.request.post(targetBase,{data:{title,kind}})).json();
  const first = await create('Arrival','subscene');
  const backdrop = await create('Courtyard','backdrop');
  const second = await create('Exchange','subscene');
  for (const target of [first,backdrop]) {
    const base = `${targetBase}/${target.id}`;
    await page.request.patch(base,{data:{prompt:'Test image'}});
    await page.request.post(base+'/jobs',{data:{action:'render'}});
    await finish(page,base,'image');
    const detail = await (await page.request.get(base)).json();
    await page.request.post(base+`/candidates/${detail.slots[0]}`,{data:{action:'select'}});
  }
  await page.goto(`/narrative?story=${story.id}&scene=${scene.id}`);
  const cards = page.locator('.narrative-target-card');
  await expect(cards).toHaveCount(3);
  await expect(cards.nth(0)).toHaveAttribute('data-target-id',backdrop.id);
  await expect(cards.nth(1)).toHaveAttribute('data-target-id',first.id);
  await expect(cards.nth(2)).toHaveAttribute('data-target-id',second.id);
  await expect(cards.nth(2).locator('img')).toHaveCount(0);
  for (const card of [cards.nth(0),cards.nth(1)]) {
    const image = card.locator('img');
    await expect(image).toBeVisible();
    await expect.poll(()=>image.evaluate(img=>img.complete && img.naturalWidth > 0)).toBe(true);
  }
  await cards.nth(1).locator('img').click();
  const picker = page.getByRole('combobox',{name:'Subscene or backdrop',exact:true});
  await expect(picker).toHaveValue(first.id);
  await expect(picker.locator('option')).toHaveText(['Courtyard · Backdrop','Arrival · Subscene','Exchange · Subscene']);
  await page.locator('#narrative-narrative').fill('A revised arrival before switching pages.');
  await picker.selectOption(backdrop.id);
  await expect(picker).toHaveValue(backdrop.id);
  await expect(page.locator('#narrative-width')).toHaveValue('1344');
  const saved = await (await page.request.get(`${targetBase}/${first.id}`)).json();
  expect(saved.narrative).toBe('A revised arrival before switching pages.');
  await picker.selectOption(second.id);
  await expect(picker).toHaveValue(second.id);
  await expect(page.locator('#narrative-title')).toHaveValue('Exchange');
  await page.locator('#narrative-title').fill('New exchange');
  await page.getByRole('button',{name:'Save inputs',exact:true}).click();
  await expect(picker.locator('option:checked')).toHaveText('New exchange · Subscene');
  await page.goBack();
  await expect(picker).toHaveValue(backdrop.id);
  await picker.selectOption(first.id);
  await expect(picker).toHaveValue(first.id);
  await expect(page.locator('#narrative-narrative')).toHaveValue('A revised arrival before switching pages.');
});
