# This is a comment. TOML files use hash symbols for comments.

title = "Zet's Magic Pipeline"

[BaseFolders]
BaseCharacterPath = "_Lib/Characters/"
BaseAssetPath = "_Lib/Assets/"
BasePipelinePath = "_Lib/Pipelines/"
BaseAIQueuePath = "_Lib/AI_Queue"

